# Generated by Django 2.2.6 on 2019-11-05 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headway', '0002_auto_20191105_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='requester',
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='recipients',
            field=models.ManyToManyField(related_name='received_feedback_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_feedback_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
